### PR TITLE
Add loading overlay to chameleon iframe while template is being generated

### PR DESCRIPTION
**Pull request by sukhrajghuman**
what do you think? could have a toast notification instead

### CODE REVIEW

**Comment by alex-page** [comment]
@sukhrajghuman this is great work. Some of the things I have noticed:
- The spinner disappears then it changes the colour. The spinner should show until the colour is changed.
- The delay was changed from 400 -> 1000. I don't think this was intentional. Remember to have a quick look at the files changed on GitHub.
- `role="alert"` would be a frustrating user experience as every time it gets shown the alert would get read. I personally would hate hearing "Loading your template" every time a new request is sent to Chameleon.
- `background-color: #ffffff63;` this should use rgba, also you should test this in IE8.
- When you use `AU-svguri` you don't need classes, width or height. Have a look at some of the other implementations of icons in the `_icons.scss` file.
- The SVG itself is quite large, look at how we have split icons into multiple lines
- Maybe a different SVG would be more appropriate. It is quite large and I don't mind a single line spinner. It would probably be less kb as well.

**Comment by sukhrajghuman** [comment]
thanks for feedback @alex-page 
- Yea my bad i forgot to remove the role='alert'
- Yeah i need to work out how to make the transition from the loader more smooth

> background-color: #ffffff63; this should use rgba, also you should test this in IE8.
- nice point

> When you use AU-svguri you don't need classes, width or height. Have a look at some of the other implementations of icons in the _icons.scss file.
yea the svg was quite large, I think a gif will be probs be better

> You are using background and background-color you can probably just use background, or change the other css to specific properties

for some reason when I put them as one, the overlay didn't show up. Will investiagte it further.

**Comment by alex-page** [comment]
Nice happy to help mate!

**Comment by alex-page** [comment]
@sukhrajghuman let me know if you are happy with the above changes.

**Comment by sukhrajghuman** [comment]
nice mate much better

**Pull request merged**
